### ISSUE TITLE
Personal Access Tokens missing

### ISSUE THREAD

**Issue by mvaker** [Asana/php-asana#13]
Hi! I think there should be a method in the client to connect using Personal Access Tokens because, as stated in Asana API docs (https://asana.com/guide/help/api/api), API Key is going to be deprecated soon. Thanks!

**Comment by noonhub** [comment]
I have added support for this and will deploy as soon as I can get a review from a team member. https://github.com/Asana/php-asana/pull/15

**Comment by mvaker** [comment]
Great! I looked up your code and everything seems alright. I'm looking forward for the approval.
Thanks!

**Comment by noonhub** [comment]
Personal access token support has been released in `0.3.0` as well as an example of usage found here: https://github.com/Asana/php-asana/blob/master/examples/example-accesstoken.php
