### ISSUE TITLE
API Keys deprecated. 

### ISSUE THREAD

**Issue by salt-lick** [Asana/php-asana#25]
On https://asana.com/developers/documentation/getting-started/auth you state:
"API Key (Deprecated) The API key has been deprecated in favor of OAuth 2.0."

However, in the readme.md file it just says that asana supports OAuth 2.
"Asana supports OAuth 2. asana handles some of the details of the OAuth flow for you."

I think you should specify that API keys are deprecated and OAuth 2 should be used instead. 

Thanks.

**Comment by marcogallotta** [comment]
Thanks for filing this issue! We are working towards cutting back on API key usage. New users cannot create API keys. Therefore we are reducing mentions of the API key where possible. Closing as wontfix.
