### ISSUE TITLE
bigint id is converted to float (in PHP < 7)

### ISSUE THREAD

**Issue by alexander-itcraft** [Asana/php-asana#28]
Hi,

Example of issue:
Lets assume Asana API returns this JSON:
{**"id":103000832048915**,"created_at":"2016-03-21T11:52:56.019Z","modified_at":"2016-03-23T15:33:03.876Z","name":"Test","notes":"Test","completed":false,"completed_at":null,"due_on":"2016-04-25","due_at":null,"workspace":{"id":11111111111111},"parent":null}

So id is **103000832048915**, and it doesn't fit 32-bit int.
That's why PHP < 7 converts it to **float(1.0300083204892E+14)**.
This breaks ID, it isn't valid anymore.

In PHP 7 it is decoded as **int(103000832048915)**

There are exists special json_decode parameter **JSON_BIGINT_AS_STRING** (for fix in PHP < 7)
However, **nategood/httpful** has rejected pull request (https://github.com/nategood/httpful/pull/189) that would make possible using this json_decode option in **Asana/php-asana**.

Best regards, Alexander.

**Comment by marcogallotta** [comment]
Thanks for reporting this, and sorry for taking so long to respond.

We're discussing this internally and are considering solutions that would likely include dropping support for 5.3 (which doesn't have JSON_BIGINT_AS_STRING).
