### ISSUE TITLE
Get tasks from active Project

### ISSUE THREAD

**Issue by davidperezgar** [Asana/php-asana#36]
Hello, I'm writing a script that every night goes to Asana and get the tasks from active project. I'm trying to get stats with other software to create a Balance Score card, but Asana does not give all details that I want. 
Just want to know what we have done in a certain period.

This is my code related with Asana:

`
$asana = new Asana(array('personalAccessToken' => $asana_token)); // Create a personal access token in Asana or use OAuth

try
{
 $asana->getProjects();
 if ($asana->hasError()) {
 echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
 return;
 }

// $asana->getData() contains an object in json with all projects
 foreach ($asana->getData() as $project) {
 echo 'Project ID: ' . $project->id . ' is ' . $project->name . '\n' . PHP_EOL;

```
 $asana->getProjectTasks($project->id);
 if ($asana->hasError()) {
 echo 'Error while trying to connect to Asana, response code: ' . $asana->responseCode;
 return;
 }
 foreach ($asana->getData() as $task) {

$asana->getTask($task->id);
 $task_detail = $asana->getData();

//var_dump($task_detail);
 if(!empty($task_detail->assignee->name)) $assignee = $task_detail->assignee->name; else $assignee = '';
 } // asana task
```

}
}
`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/182694718843648/208434230185913)

**Comment by markchua** [comment]
It is not clear what you actually want to achieve. Please provide more details.

**Comment by davidperezgar** [comment]
Hello @markchua . 
I'd like to get all tasks from active projects, but it stops in the middle becouse of Asana API pagination. I'd like to get that database. Any idea to solve it? 

Thanks!

**Comment by markchua** [comment]
What error are you getting? Is it something related to pagination offset expiring? If so what you need to do is pre-save all the the task ids you want to explore such that pagination does not timeout and then go through the list of tasks ids that you saved.
Alternatively, you can specify which fields in the task you care about so that you don't need to request for each task individually.

**Comment by davidperezgar** [comment]
how can i keep the pagination? is there any function?

**Comment by markchua** [comment]
I don't think the pagination is exposed to you- you'd need to hit the api directly if you want to keep the pagination. The problem likely isn't that though- it's that the pagination is expiring which means even if you keep it you can't use it once it expires. You should read my last comment.
