### ISSUE TITLE
Asana API section endpoints

### ISSUE THREAD

**Issue by marashlyansuren** [Asana/php-asana#41]
Asana api support section endpoints but php-asana sdk is not, why ?

![selection_002](https://user-images.githubusercontent.com/3089635/30484181-ad221436-9a3a-11e7-81f9-f4b7dd056a75.png)
![selection_003](https://user-images.githubusercontent.com/3089635/30484191-b1d08b5c-9a3a-11e7-87d8-6b8cf68f829d.png)

**Comment by praecipula** [comment]
Hi there @marashlyansuren,

We've had some difficulty finding the time or priority to get some of our newer API features implemented across all of our client libraries. While it seems like an easy enough task to do for one of them, we maintain 5 (well, 6 including our API explorer) that are all generated at the same time and have to have some love before bumping to a new version.

One thing you might try is to look at the branch called "api-meta-incoming" (https://github.com/Asana/php-asana/tree/api-meta-incoming). It has the autogenerated files from our documentation with stubs for new resources; the remaining work is to subclass the base class in https://github.com/Asana/php-asana/tree/api-meta-incoming/src/Asana/Resources/Gen with the new resource in https://github.com/Asana/php-asana/tree/api-meta-incoming/src/Asana/Resources, change the file that you screenshotted to add the new resource, and create tests in https://github.com/Asana/php-asana/blob/api-meta-incoming/tests/Asana/ResourcesTest.php (which badly needs a refactor anyway :/) Hopefully that makes sense.

We've been discussing internally ways to make our client libraries more maintainable, so thanks for your patience and feedback! I'm sure sooner or later (sooner being if we hear more from the community!) we'll be able to prioritize a pass through our libraries.

**Comment by cy-josh** [comment]
Any progress on integrating this?

**Comment by joetrollo** [comment]
These were added as part of a bulk update in #53
