### ISSUE TITLE
Exception should be more detailed

### ISSUE THREAD

**Issue by igorsantos07** [Asana/php-asana#44]
Currently we have to jump inside the Exception response's body to uncover what happened on an `AsanaError`. This is, to say the least, counter-productive. Details should be given on a specific and clear exception field, or even inside its message.

**Comment by praecipula** [comment]
Hi @igorsantos07,

Thanks for the feedback! When you mention an `AsanaError`, do you mean any class that extends `AsanaError`, or the `AsanaError` itself (that is, it's a more generic error that isn't one that's handled by a more specific subclass of `AsanaError`)

I think I understand what you're getting at here - that the message that comes back in the HTTP response could be made more readily available to any exception that gets thrown (for ease of printing / logging) is that correct?

I think that's a good idea, and we'll put it in our backlog for the next time we get to batch features into our client libraries. Thanks!

**Comment by praecipula** [comment]
➤ Matt Bramlage commented:

I asked for more details and said that we'd evaluate the suggestion when we get back to our client libraries.
