### ISSUE TITLE
Get tasks by name

### ISSUE THREAD

**Issue by cemeai** [Asana/php-asana#48]
Hello, I'm trying to use php-asana to add comments to an asana task.
I get the tasks from a project but i want to get them by task 'name' is there a way to acheive this?

Code:
```
$tasks = $asana_client->tasks->findByProject('project_id', array('name' => 'task_name'));
foreach ($tasks as $task) {
	var_dump($task);
}
```
This gets me all the tasks in the project, I don't know if adding the name as a parameter works or is it just ignoring it.

Also is there a documentation for this library?

**Comment by jjschnei** [comment]
Hi, thanks for reaching out.  Unfortunately, there is no library specific documentation at this time.  All of the resources and their respective methods are located in the [Gen folder of the library](https://github.com/Asana/php-asana/tree/b9e9fa8a9c00dd7d831112f0e727562a43311159/src/Asana/Resources/Gen).  We do have [API docs](https://asana.com/developers/api-reference/attachments), but these are not specific to the PHP client library.  

The only way to get a task by name would be to use the [typeahead endpoint](https://asana.com/developers/api-reference/typeaheads).  You can see the [PHP method on line 72](https://github.com/Asana/php-asana/blob/b9e9fa8a9c00dd7d831112f0e727562a43311159/src/Asana/Resources/Gen/WorkspacesBase.php). I hope that helps.

**Comment by praecipula** [comment]
➤ Jeff Schneider commented:

Another example of a user needing client library documentation.
