### ISSUE TITLE
GET TASK - missing field start_on in response!!

### ISSUE THREAD

**Issue by paoloperego** [Asana/php-asana#50]
getting a task data, the field start_on is missing! is possibile to retrieve it? is very important in order to manage tasks using client! I also tried the CURL GET call but that parameter is missing there too!!

**Comment by paoloperego** [comment]
SOLVED: it had to be asked otherwise it won't be returned... sorry.

**Comment by praecipula** [comment]
Ah, sorry @paoloperego - I'm glad you figured it out! I believe we intended to return start_on by default with the launch of our Timeline feature but haven't yet done so. I've updated our API team that this still seems like something that it makes sense to do, thanks for the feedback!
