### ISSUE TITLE
Some fields does not work. 

### ISSUE THREAD

**Issue by TheMartes** [Asana/php-asana#51]
Hi, 

I've been working with asana-php last week, and i need to get from my tasks some fields, that seems your api doesn't returning. for example. GET request on `html_text` on stories, did not return anything. Same as GET request `preview_url` & `download_url` at attachments.  

At attachments, the function for returning attachments is 
```
public function showAttachments($task)
{
        $attachments = $this->client->attachments->findByTask($task, [
            'fields' => [
                'name', 'view_url'
            ]
        ]);

        return $attachments;
}
```
and it returns following object
```
object(stdClass)#839 (2) { ["id"]=> int(698381732394846) ["name"]=> string(26) "Demo 05.06.2018 15:57.html" }
```

Thank you for quick reply.

**Comment by theaeolianmachine** [comment]
Hi @TheMartes,

Taking a look at https://github.com/Asana/php-asana/blob/b8e73cd8317467307994008d61e18bd518ae4b7e/src/Asana/Resources/Gen/AttachmentsBase.php#L38, it looks like you need to specify fields in the options array, which is the third argument to `findByTask`. Can you try this out by passing an empty array as the second arg, and your array with the fields specified as the _third_ argument?
