### ISSUE TITLE
Get all tasks by name user

### ISSUE THREAD

**Issue by medness** [Asana/php-asana#55]
Hello, everyone, help me figure it out. Can I select all tasks by user name.

**Comment by jjschnei** [comment]
Hey @medness, you can find all of the resource methods in the gen folder:  https://github.com/Asana/php-asana/tree/master/src/Asana/Resources/Gen

To find all tasks assigned to a specific user, you can use the `findAll` method, which you can find on line 145 of [Gen/TasksBase.php](https://github.com/Asana/php-asana/blob/master/src/Asana/Resources/Gen/TasksBase.php):

```
    /**
     * Returns the compact task records for some filtered set of tasks. Use one
     * or more of the parameters provided to filter the tasks returned. You must
     * specify a `project` or `tag` if you do not specify `assignee` and `workspace`.
     *
     * @return response
     */
    public function findAll($params = array(), $options = array())
    {
        return $this->client->getCollection("/tasks", $params, $options);
    }  
```
