### ISSUE TITLE
Is it possible to use styling in the note call

### ISSUE THREAD

**Issue by flipbosch** [Asana/php-asana#57]
I want to maintain the styling of the notes in my issues.
According to the official API documentation this should be possible. 

https://asana.com/developers/documentation/getting-started/rich-text

But when I try its not working with this PHP API. I also tried to use `html_notes` instead `notes` but this is not available (anymore).

Here an example what I try to do: 

```
# Update tasks
$myTask = $client->tasks->update(111111, array(
    "name" => " Updated:demo task created at " . date('m/d/Y h:i:s a'),
    "notes"  => "This is some <strong>nice</strong> description /n /n And a blank line below it"
));
```

**Comment by rossgrambo** [comment]
Hey @flipbosch ,

You'll need to hit html_notes in order for it to parse the rich text, wrap the contents in a body tag, and use backslash instead of forward slash. Try:

    "html_notes"  => "<body>This is some <strong>nice</strong> description \n \n And a blank line below it</body>"

Best,
Ross
