### ISSUE TITLE
Fatal error: Class 'Error' not found in <fullpath>\src\Asana\Dispatcher\OAuthDispatcher.php on line 49

### ISSUE THREAD

**Issue by elizabethmeyer** [Asana/php-asana#6]
When attempting to use the Asana API PHP library from here https://github.com/Asana/php-asana I get the following error:

Fatal error: Class 'Error' not found in \src\Asana\Dispatcher\OAuthDispatcher.php on line 49

I realise the error is because the authorization is not working - but how can I fix it to actually throw an exception?

**Comment by slobak** [comment]
Ah, this is a typo, probably. We should change it to `new Exception` rather than `new \Error`, I'm pretty sure.

**Comment by slobak** [comment]
Fixed in v0.1.4. Thanks for reporting!
