### ISSUE TITLE
'headers' config is replaced by automatically-generated request 'headers'

### ISSUE THREAD

**Issue by pridumkuvatyj** [Asana/php-asana#60]
I'm setting `Asana\Client` like this:
```php
$options = [
    'headers' => [
        'asana-enable' => 'string_ids'
    ]
];
$client = AsanaClient::accessToken('***', $options);
```

But when I'm trying to post a comment to a task like this:
```php
$gid = '1136900226906650';
$r = $client->addComment($gid, [
    'text' => 'test comment',
]);
```

The headers from client config are replaced during a simple merge with automatically generated `content-type` header from request: https://github.com/Asana/php-asana/blob/master/src/Asana/Client.php#L232-L245

There should be a recursive merge in https://github.com/Asana/php-asana/blob/master/src/Asana/Client.php#L83

P.S. Asana version is 0.9.0

**Comment by rossgrambo** [comment]
Thank you for finding this, and the easy to reproduce steps.

I just released v0.9.1 https://github.com/Asana/php-asana/releases/tag/v0.9.1 where this should be resolved.

Let me know if you have any issues!

**Comment by rossgrambo** [comment]
Nevermind. I had to revoke 0.9.1, as this solved your issue, but caused another one. I'll let you know when I release it again.

**Comment by rossgrambo** [comment]
Okay, released again. Let me know if you have any issues!

https://github.com/Asana/php-asana/releases/tag/v0.9.1

**Comment by pridumkuvatyj** [comment]
@rossgrambo Can you please manually update the package version on Packagist? It still has `v0.9.0` as the latest tag: https://packagist.org/packages/asana/asana
Thanks!

**Comment by pridumkuvatyj** [comment]
@rossgrambo I'll wait for packagist :) No ETA available?

**Comment by thedotedge** [comment]
@rossgrambo any luck with publishing? Still broken 0.9.0 on https://packagist.org/packages/asana/asana.

**Comment by rossgrambo** [comment]
Still working through the publishing. Looks like our travis build is silently failing when pushing to packagist. We're working on doing a manual deploy today. 

Unless something blocks us, it should be out today. I'll keep this issue open until it's deployed.

**Comment by rossgrambo** [comment]
Alright, it should be deployed now. Sorry for the delay on this one! https://packagist.org/packages/asana/asana#v0.9.1
