### ISSUE TITLE
Client.php does not return a full response object

### ISSUE THREAD

**Issue by shawnnaquin** [Asana/php-asana#63]
## Expected Behavior
The Client.php returns a full response object, with headers

## Actual Behavior
The Client.php returns only the body of the response object

This response headers are important since the response is expected to include a `Retry-After` header in the event of a rate limit exception, according to the documentation

https://asana.com/developers/documentation/getting-started/rate-limits

## Steps to Reproduce the Problem

  1. make a request
  2. include `array('full_payload'=>TRUE)` in the options
  3. only the body of the message is returned
Client.php ~:84
```
                if ($options['full_payload']) {
                    return $response->body;
                } else {
                    return $response->body->data;
                }
```
## Specifications

  - Version: v0.9.1
  - Platform: Composer / Nginx
  - Subsystem: Laravel

**Comment by rossgrambo** [comment]
Hey @shawnnaquin,

Sadly, I believe this is expected. As the docs say:

> full_payload (default: false): return the entire JSON response instead of the 'data' propery (default for collection methods and events.get)

To return the entire "JSON" response wouldn't include the headers, but basically just the data envelope ( ex:  "data : { <default response> }" ).

I believe the motive behind these libraries was to abstract out the retry-after logic, so the library would automatically handle that for you. In the tests here: https://github.com/Asana/php-asana/blob/f6aa3cfcb272218a1f1357f3ee96e57d952c7169/tests/Asana/ClientTest.php#L214 it appears to be testing that the retry logic is working as expected. 

Were you having any issues with the retry logic? Or were there other fields on the response object you were looking for? I do agree that getting the response object should be an option.

**Comment by shawnnaquin** [comment]
Running several jobs concurrently results in the `Rate Limit Enforced` message thrown as the response body. I was hoping to get a retry-after header in order to wait the correct amount of time.

I probably just need to limit my connections more appropriately, I'm running several concurrent jobs batched by date ranges, which each make a call for every day.

**Comment by rossgrambo** [comment]
Yeah that makes sense. 

If you hit the Concurrent Rate Limit, I think you'll be better off not listening to the retry-after header. We can't predict when your previous requests will finish (some take 60 secs while others take 5 seconds), so the retry-after header is set to our request timeout (~120 seconds) for concurrent rate limit enforcement.

Our concurrent request limit is 10 at a time, so I think the best approach is to queue your requests in some way to ensure no more than 10 are active at a time.

**Comment by rossgrambo** [comment]
I'm gonna close this for now, but let me know if I should open it back up! 😄

**Comment by shawnnaquin** [comment]
Hey Ross, 

Thanks again! 

The concurrent limit of 10 helped me out, I'm currently making a max of 8 get requests and the API is working fine.

It may be helpful for other developers to mention the concurrent limit of 10 in the docs. 
( I found in the real-world, 8 works best for 100% success ).

**Comment by rossgrambo** [comment]
Great idea! I'll make a task for it! 😄
