### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by amityweb** [Asana/php-asana#64]
Does this project still work? I am getting errors. Firstly, 
`$workspaceId = $me->workspaces[0]->id;`
becomes
`$workspaceId = $me->workspaces[0]->gid;`

Then after that, creating the project using your example results in:
```
PHP Fatal error:  Uncaught Asana\Errors\InvalidRequestError: Invalid Request in /home/pi/Scripts/Asana/php-asana/src/Asana/Errors/AsanaError.php:28
Stack trace:
#0 /home/pi/Scripts/Asana/php-asana/src/Asana/Client.php(98): Asana\Errors\AsanaError::handleErrorResponse(Object(Httpful\Response))
#1 /home/pi/Scripts/Asana/php-asana/src/Asana/Client.php(247): Asana\Client->request('POST', '/workspaces/121...', Array)
#2 /home/pi/Scripts/Asana/php-asana/src/Asana/Resources/Gen/ProjectsBase.php(58): Asana\Client->post('/workspaces/121...', Array, Array)
#3 /home/pi/Scripts/Asana/move_due_tasks_to_today.php(17): Asana\Resources\Gen\ProjectsBase->createInWorkspace('123456789', Array)
#4 {main}
  thrown in /home/pi/Scripts/Asana/php-asana/src/Asana/Errors/AsanaError.php on line 28
```

Do I persevere and try to address the issues or is this project dead? 

Thanks

**Comment by amityweb** [comment]
I think it still may work, just have to figure it out from the API documentation as the GitHub documentation is not clear enough. e.g. the calls return a collection, and you have to iterate through them. and we have to reference the api here and look in the file system to find out what methods to call. 

But needs to be updated anyway, as per the ID issue above.

**Comment by rossgrambo** [comment]
Hey @amityweb,

It looks like this library does a bad job of surfacing errors. The error code you're likely getting is: 

`"Missing required `team` field"`

Assuming you're in an organization and not a workspace. Changing the create request to:

`$client->projects->createInWorkspace("1234567890", array('name' => 'Test Project', 'team' => '987654321'));`

Should fix your issue. 

This project is not dead but it definitely needs some love. We've been revamping how all of our libraries are generated, and it has lead to us neglecting them in the meantime. Sorry if there are some cobwebs while we push through with this change. You should start seeing updates within a couple of months.

**Comment by amityweb** [comment]
Thanks. I have managed to get what I want done and get passed this error, just needed figuring out what method exist in the files, and then referencing the API docs to know what params are needed to pass... so it does take some figuring out as I did not think the docs here on GitHub was very clear. 

But I posted the error just because I thought following the firs issue with the id/gid then maybe thre are more issues, but in fact it was just figuring it all out. The issue with id -> gid exists though.

**Comment by tmiecz** [comment]
> referencing the API docs to know what params are needed to pass

Hi @amityweb - could you possibly tell us what the solution was? I'm going crazy here trying to figure it out and [the docs I found](https://developers.asana.com/docs/#create-a-project-in-a-workspace) are not very clear, so I added it all, and I'm still getting an error.

`$project = $client->projects->createInWorkspace(
        $workspaceId,
        array(
            'name' => $projectName,
            'archived' => false,
            'color' => 'light-green',
            'current_status' => NULL,
            'default_view' => 'list',
            'due_date' => NULL,
            'due_on' => NULL,
            'html_notes' => $projectNotes,
            'is_template' => false,
            'notes' => $projectNotes,
            'owner' => $asana_owner,
            'public' => false,
            'start_on' => NULL,
            'team' => $teamId
        )
    );`

Everything else works, this is the only thing I'm unable to get through. Any help would be appreciated.

**Comment by amityweb** [comment]
I am no longer using createInWorkspace. Instead of using code to add my emails into Asana which is what I wanted, I used a 3rd party system called Integromat (its like Zapier) to do it. 

Instead I now have the code below which finds all tasks assigned to me with a due date of today or less and adds it into a Today project I created for my Today tasks (because Asanas Today view is rubbish so I have a Today project I use and this automation adds all todays tasks into it automatically). This works for me, so maybe you can figure it out from this. 

I only had two issues though:

1) Fetching the $workspaceId is wrong in the docs, so as per my correction at the top it worked, then 
2) Figuring out what end points I can call and then the attributes passed to them was hard, as the documentation does not cover this, so I had to use Asanas API doc to see whats available, and then search this projects files to see what I need to call to access the Asana API end points. So it was tricky but possible. 

```
<?php
// https://github.com/Asana/php-asana

// Token
$token = '0/12345678998765432'; // Replace with your access token

// Get today project
$today_gid = '123456789'; // Replace with the ID of your project

require 'php-asana/vendor/autoload.php';

$client = Asana\Client::accessToken($token);

$me = $client->users->me();

$myid = $me->gid;
$workspaceid = $me->workspaces[0]->gid;

$params = array(
	'assignee.any' => $myid,
	'due_on.before' => date('Y-m-d'),
	'completed' => 0,
	'projects.not' => $today_gid
);
$tasks = $client->tasks->searchInWorkspace($workspaceid, $params);
    
foreach ($tasks as $task)
{
	// Check if task in today project
	$projects = $client->tasks->projects($task->gid);

	echo $task->name . "\n";
	
	$params = array(
		'project' => $today_gid,
	);
	$addProject = $client->tasks->addProject($task->gid, $params);
	
	$tasknames[] = $task->name;
	
}
```

**Comment by tmiecz** [comment]
Thanks a lot for replying so fast. I was hoping that you got the **"createProject"** to work, but in your code it looks like you hardcoded an existing project and assign the task to it. 

I tried it with 3 different asana client libraries, and this being the **"official"** one, I figured it would work, but I guess they must have introduced some sort of bug there. I guess I'll try to dig deeper into documentation and see if I can get a response error of some sort because **"Invalid Request"** is simply not enough. 

Good for you that you got it to work with their competitor. I'll try to figure something out, if I find a workaround I'll post it back here.

**Comment by rossgrambo** [comment]
@tmiecz , if you want to look into the error, our library allows you to if you catch the error. 

```
try {
    $project = $client->projects->createInWorkspace( $workspaceId, array( 'name' => $projectName, 'archived' => false, 'color' => 'light-green', 'current_status' => NULL, 'default_view' => 'list', 'due_date' => NULL, 'due_on' => NULL, 'html_notes' => $projectNotes, 'is_template' => false, 'notes' => $projectNotes, 'owner' => $asana_owner, 'public' => false, 'start_on' => NULL, 'team' => $teamId ) );
} catch (\Asana\Errors\AsanaError $e) {
    var_dump($e->response);
}
```

That will log exactly what the request and response were. The API responds with pretty good error messages, so I'm surprised our library doesn't surface these by default.



@amityweb , sorry about making you do a workaround to find endpoints. We're moving to more consistent endpoints and we have a PR out for it now. Hopefully that will make the methods much easier to self-discover.


Going to close issue for now but let me know if you have any other questions!
