### ISSUE TITLE
What are the other 2 parameters of get function?

### ISSUE THREAD

**Issue by jamols09** [Asana/php-asana#69]
What are the uses of 2 parameters under get function, and how do I use this for including the due_on on the result?

**Comment by rossgrambo** [comment]
This will get you due_on.

```php
$tasks = $client->tasks->getTasksForProject("1234567890", array("opt_fields" => "name,due_on"));
```

The params you're asking about `$params` and `$options`. `$params` just appends things as url params. `$options` handles misc other options, like `headers`, `files`, etc.

In your situation, you can pass "opt_fields" as a param, or pass "fields" to options. They'll both do the same thing.

**Comment by jamols09** [comment]
I was not sure on the structure of using the 2nd parameter but my presumption on the format is right, but I just can't display if it's right or wrong because the only function that works for me is `get, post etc` when using other function like `getTasksForProject`  `getTasksForSection` it wont display data.

**Comment by rossgrambo** [comment]
```php
    /** Get subtasks from a task
     *
     * @param string $task_gid  (required) The task to operate on.
     * @param array $params
     * @param array $options
     * @return response
     */
    public function getSubtasksForTask($task_gid, $params = array(), $options = array()) {
        $path = "/tasks/{task_gid}/subtasks";
        $path = str_replace("{task_gid}", $task_gid, $path);
        return $this->client->getCollection($path, $params, $options);
    }

    /** Get a task
     *
     * @param string $task_gid  (required) The task to operate on.
     * @param array $params
     * @param array $options
     * @return response
     */
    public function getTask($task_gid, $params = array(), $options = array()) {
        $path = "/tasks/{task_gid}";
        $path = str_replace("{task_gid}", $task_gid, $path);
        return $this->client->get($path, $params, $options);
    }
```

These are those functions. They just call `get` or `getcollection` under the hood. I would be surprised if `get` worked for you but `getTask` did not. 

If you're using "getTasksForSection" or "getTasksForProject", they return an iterator, and you'll have to iterate them to see data:
```php
$tasks = $client->tasks->getTasksForProject("1234567890", array("opt_fields" => "name,due_on"));
foreach ($tasks as $task) {
        var_dump($task);
}
```
